name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/pages.yml'

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Stable Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install OpenBLAS
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Generate Cargo Docs
        env:
          RUSTDOCFLAGS: "--html-in-header docs/header.html -D warnings"
        run: cargo doc --no-deps --all-features

      - name: Add Redirect Index Page
        run: |
          echo '<meta http-equiv="refresh" content="0; url=helix/index.html">' > target/doc/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/doc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
